### PR TITLE
SERV-650 Merge Payara API pages

### PR DESCRIPTION
**Pull request by shub8968**
[SERV-650] Merge Payara API pages

[SERV-650]: https://payara.atlassian.net/browse/SERV-650

### CODE REVIEW

**Review by AlanRoth — CHANGES_REQUESTED** [review]
image

There is another public API that needs merging that I highlighted I believe.

Also, since there is only a single page for Payara Micro API, it is best to move micro-api up a level and rename it to Payara Micro API.

**Comment by shub8968** [comment]
@AlanRoth,

That Public API is different from Payara Micro API.

**Comment by shub8968** [comment]
@AlanRoth,

Should I level up JCache in Payara Micro in this PR only as it is too a single page?

**Comment by AlanRoth** [comment]
> @AlanRoth,
> 
> Should I level up JCache in Payara Micro in this PR only as it is too a single page?

Sure

**Pull request merged**
